/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ssatr.lab1.exercise4.presentation;

import java.util.List;
import java.time.LocalDateTime;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import ssatr.lab1.exercise4.model.Buyer;
import ssatr.lab1.exercise4.model.Ticket;
import ssatr.lab1.exercise4.service.TicketsManager;

/**
 *
 * @author User
 */
public class TicketInterface extends javax.swing.JFrame {
    private TicketsManager tm = new TicketsManager();
    private ArrayList<Ticket> ticketList;
    /**
     * Creates new form TicketInterface
     */
    public TicketInterface() {
        this.ticketList = new ArrayList<>();
        ticketList.add(new Ticket("Opera", LocalDateTime.of(2025, 
                                           Month.SEPTEMBER, 20, 21, 30), "VIP", 200));
        ticketList.add(new Ticket("Rock Concert", LocalDateTime.of(2025, 
                                           Month.AUGUST, 15, 19, 30), "VIP", 100));
        ticketList.add(new Ticket("EDM", LocalDateTime.of(2025, 
                                           Month.DECEMBER, 18, 12, 30), "VIP", 120));
        ticketList.add(new Ticket("Jazz", LocalDateTime.of(2025, 
                                           Month.JULY, 9, 20, 00), "VIP", 150));
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        appTabbedPanel = new javax.swing.JTabbedPane();
        purchaseJPanel = new javax.swing.JPanel();
        buyerPanel = new javax.swing.JPanel();
        nameTextField = new javax.swing.JTextField();
        surenameTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        surenameLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        phoneNumberTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        eventTicketPanel = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        eventLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        eventNamesComboBox = new javax.swing.JComboBox<>();
        dateTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        ticketTypeTextField = new javax.swing.JTextField();
        ticketTypeLabel = new javax.swing.JLabel();
        buyTicketButton = new javax.swing.JButton();
        validateTicketPanel = new javax.swing.JPanel();
        ticketValidationPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        selectTicketButton = new javax.swing.JButton();
        ticketPathTextField = new javax.swing.JTextField();
        validateTicketButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ticket Manager");
        setName("TicketFrame"); // NOI18N
        setResizable(false);

        buyerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        nameLabel.setText("Name");

        surenameLabel.setText("Surename");

        addressLabel.setText("Address");

        phoneNumberLabel.setText("Phone Number");

        emailLabel.setText("Email");

        javax.swing.GroupLayout buyerPanelLayout = new javax.swing.GroupLayout(buyerPanel);
        buyerPanel.setLayout(buyerPanelLayout);
        buyerPanelLayout.setHorizontalGroup(
            buyerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyerPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(buyerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLabel)
                    .addComponent(surenameLabel)
                    .addComponent(emailLabel)
                    .addComponent(addressLabel)
                    .addComponent(phoneNumberLabel))
                .addGap(18, 18, 18)
                .addGroup(buyerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(addressTextField)
                    .addComponent(emailTextField)
                    .addComponent(surenameTextField)
                    .addComponent(nameTextField))
                .addContainerGap())
        );
        buyerPanelLayout.setVerticalGroup(
            buyerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyerPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(buyerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buyerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surenameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buyerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buyerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buyerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberLabel)
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        eventTicketPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        dateLabel.setText("Date");

        eventLabel.setText("Event");

        priceLabel.setText("Price");

        List<String> ticketNames = new ArrayList<String>();
        for(Ticket ticket : ticketList){
            ticketNames.add(ticket.getEventName());
        }
        eventNamesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(ticketNames.toArray(new String[0])));
        eventNamesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventNamesComboBoxActionPerformed(evt);
            }
        });

        dateTextField.setText(ticketList.get(eventNamesComboBox.getSelectedIndex()).getEventDate().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm")));
        dateTextField.setEnabled(false);

        priceTextField.setEditable(false);
        priceTextField.setText(String.valueOf(ticketList.get(eventNamesComboBox.getSelectedIndex()).getTicketPrice()));
        priceTextField.setEnabled(false);

        ticketTypeTextField.setText(String.valueOf(ticketList.get(eventNamesComboBox.getSelectedIndex()).getTicketType()));
        ticketTypeTextField.setEnabled(false);

        ticketTypeLabel.setText("Type");

        buyTicketButton.setText("Buy Ticket");
        buyTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyTicketButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eventTicketPanelLayout = new javax.swing.GroupLayout(eventTicketPanel);
        eventTicketPanel.setLayout(eventTicketPanelLayout);
        eventTicketPanelLayout.setHorizontalGroup(
            eventTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventTicketPanelLayout.createSequentialGroup()
                .addGroup(eventTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eventTicketPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(eventTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ticketTypeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(eventTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ticketTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(eventTicketPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(eventTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buyTicketButton)
                            .addGroup(eventTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(eventTicketPanelLayout.createSequentialGroup()
                                    .addComponent(eventLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(eventNamesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(eventTicketPanelLayout.createSequentialGroup()
                                    .addComponent(dateLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        eventTicketPanelLayout.setVerticalGroup(
            eventTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventTicketPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(eventTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventNamesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(eventTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(eventTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(eventTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticketTypeLabel))
                .addGap(18, 18, 18)
                .addComponent(buyTicketButton)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout purchaseJPanelLayout = new javax.swing.GroupLayout(purchaseJPanel);
        purchaseJPanel.setLayout(purchaseJPanelLayout);
        purchaseJPanelLayout.setHorizontalGroup(
            purchaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchaseJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buyerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eventTicketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        purchaseJPanelLayout.setVerticalGroup(
            purchaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchaseJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(purchaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buyerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventTicketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        appTabbedPanel.addTab("Purchase", purchaseJPanel);

        ticketValidationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Ticket Path");

        selectTicketButton.setText("Select Ticket");

        ticketPathTextField.setEnabled(false);

        validateTicketButton.setText("Validate Ticket");

        javax.swing.GroupLayout ticketValidationPanelLayout = new javax.swing.GroupLayout(ticketValidationPanel);
        ticketValidationPanel.setLayout(ticketValidationPanelLayout);
        ticketValidationPanelLayout.setHorizontalGroup(
            ticketValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketValidationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ticketValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ticketValidationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ticketPathTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ticketValidationPanelLayout.createSequentialGroup()
                        .addGap(0, 184, Short.MAX_VALUE)
                        .addComponent(selectTicketButton)
                        .addGap(4, 4, 4)
                        .addComponent(validateTicketButton)))
                .addContainerGap())
        );
        ticketValidationPanelLayout.setVerticalGroup(
            ticketValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketValidationPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(ticketValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ticketPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(ticketValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectTicketButton)
                    .addComponent(validateTicketButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout validateTicketPanelLayout = new javax.swing.GroupLayout(validateTicketPanel);
        validateTicketPanel.setLayout(validateTicketPanelLayout);
        validateTicketPanelLayout.setHorizontalGroup(
            validateTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(validateTicketPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ticketValidationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );
        validateTicketPanelLayout.setVerticalGroup(
            validateTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(validateTicketPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticketValidationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        appTabbedPanel.addTab("Validate", validateTicketPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(appTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void buyTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyTicketButtonActionPerformed
        // TODO add your handling code here:
        
        Ticket ticket = tm.generateTicket(ticketList.get(eventNamesComboBox.getSelectedIndex()));
        Buyer buyer = new Buyer(nameTextField.getText(), surenameTextField.getText(), emailTextField.getText(), phoneNumberTextField.getText(), addressTextField.getText(), 
                ticket, LocalDateTime.now().toString());
        
        System.out.println(buyer.toString());
        
    }//GEN-LAST:event_buyTicketButtonActionPerformed

    private void eventNamesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventNamesComboBoxActionPerformed
        // TODO add your handling code here:
        priceTextField.setText(String.valueOf(ticketList.get(eventNamesComboBox.getSelectedIndex()).getTicketPrice()));
        ticketTypeTextField.setText(ticketList.get(eventNamesComboBox.getSelectedIndex()).getTicketType());
        dateTextField.setText(ticketList.get(eventNamesComboBox.getSelectedIndex()).getEventDate().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm")));
    }//GEN-LAST:event_eventNamesComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(TicketInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(() -> {
            new TicketInterface().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTabbedPane appTabbedPanel;
    private javax.swing.JButton buyTicketButton;
    private javax.swing.JPanel buyerPanel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel eventLabel;
    private javax.swing.JComboBox<String> eventNamesComboBox;
    private javax.swing.JPanel eventTicketPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JPanel purchaseJPanel;
    private javax.swing.JButton selectTicketButton;
    private javax.swing.JLabel surenameLabel;
    private javax.swing.JTextField surenameTextField;
    private javax.swing.JTextField ticketPathTextField;
    private javax.swing.JLabel ticketTypeLabel;
    private javax.swing.JTextField ticketTypeTextField;
    private javax.swing.JPanel ticketValidationPanel;
    private javax.swing.JButton validateTicketButton;
    private javax.swing.JPanel validateTicketPanel;
    // End of variables declaration//GEN-END:variables
}
